# Moore-TDMPC Configuration

# Environment setup
env_type: "MooreMultiTask"
n_contexts: 10  # Number of tasks/contexts

# Model dimensions
obs_dim: 24
action_dim: 6
hidden_dim: 256

# Moore-specific parameters
n_experts: 4
moore_temperature: 0.5
use_softmax: true

# TD-MPC parameters
gamma: 0.99
stddev: 0.1
actor_updates: 1
use_ema: true
ensemble_size: 5  # Q-functions ensemble size

# Training parameters
update_freq: 2
seed: 42

# Hardware
device: "cuda" # Will fall back to CPU if CUDA not available

# 默认参数
defaults:
  - override hydra/launcher: submitit_local

# 任务和环境
task: mt30
obs: state
multitask: true

# 训练参数
steps: 10_000_000
batch_size: 256
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 100_000
exp_name: moore-tdmpc2-mt30

# 评估参数
eval_freq: 2000
eval_episodes: 10

# Moore架构参数
moore:
  n_experts: 4
  temperature: 1.0
  use_softmax: true
  debug_task_emb: false

# 规划参数
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# Actor参数
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# 模型参数
model_size: 5
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# Critic参数
num_bins: 101
vmin: -10
vmax: +10

# 日志参数
wandb_project: moore-tdmpc2
wandb_entity: OA-MBRL
wandb_silent: false
enable_wandb: true
save_csv: true
save_video: false
save_agent: true

# 其他参数
compile: true

# 自动设置的参数（不需要修改）
work_dir: ???
task_title: ???
tasks: ???
obs_shape: ???
episode_length: ???
obs_shapes: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???
data_dir: '/media/levi/Singe4linux/Moore-TDMPC/TDMPC2/data/mt30'
